<?php
//////////////////////////////////
//
//  Vitaliy Pavlenko
//  11/28/12
//
//  Generates BS advice.
//

$bs_verb = array(
    'aggregate',
    'architect',
    'benchmark',
    'brand',
    'cultivate',
    'deliver',
    'deploy',
    'disintermediate',
    'drive',
    'e-enable',
    'embrace',
    'empower',
    'enable',
    'engage',
    'engineer',
    'enhance',
    'envisioneer',
    'evolve',
    'expedite',
    'exploit',
    'extend',
    'facilitate',
    'generate',
    'grow',
    'harness',
    'implement',
    'incentivize',
    'incubate',
    'innovate',
    'integrate',
    'iterate',
    'leverage',
    'matrix',
    'maximize',
    'mesh',
    'monetize',
    'morph',
    'optimize',
    'orchestrate',
    'productize',
    'recontextualize',
    'redefine',
    'reintermediate',
    'reinvent',
    'repurpose',
    'revolutionize',
    'scale',
    'seize',
    'strategize',
    'streamline',
    'syndicate',
    'synergize',
    'synthesize',
    'target',
    'transform',
    'transition',
    'unleash',
    'utilize',
    'visualize',
    'whiteboard');

$bs_adj = array('back-end',
    'best-of-breed',
    'bleeding-edge',
    'bricks-and-clicks',
    'clicks-and-mortar',
    'collaborative',
    'compelling',
    'cross-platform',
    'cross-media',
    'customized',
    'cutting-edge',
    'distributed',
    'dot-com',
    'dynamic',
    'e-business',
    'efficient',
    'end-to-end',
    'enterprise',
    'extensible',
    'frictionless',
    'front-end',
    'global',
    'granular',
    'holistic',
    'impactful',
    'innovative',
    'integrated',
    'interactive',
    'intuitive',
    'killer',
    'leading-edge',
    'magnetic',
    'mission-critical',
    'next-generation',
    'one-to-one',
    'open-source',
    'out-of-the-box',
    'plug-and-play',
    'proactive',
    'real-time',
    'revolutionary',
    'robust',
    'scalable',
    'seamless',
    'sticky',
    'strategic',
    'synergistic',
    'transparent',
    'turn-key',
    'ubiquitous',
    'user-centric',
    'value-added',
    'vertical',
    'viral',
    'virtual',
    'visionary',
    'web-enabled',
    'wireless',
    'world-class');

$bs_noun = array(
    'action-items',
    'applications',
    'architectures',
    'bandwidth',
    'channels',
    'communities',
    'content',
    'convergence',
    'deliverables',
    'e-business',
    'e-commerce',
    'e-markets',
    'e-services',
    'e-tailers',
    'experiences',
    'eyeballs',
    'functionalities',
    'infomediaries',
    'infrastructures',
    'initiatives',
    'interfaces',
    'markets',
    'methodologies',
    'metrics',
    'mindshare',
    'models',
    'networks',
    'niches',
    'paradigms',
    'partnerships',
    'platforms',
    'portals',
    'relationships',
    'ROI',
    'synergies',
    'web-readiness',
    'schemas',
    'solutions',
    'supply-chains',
    'systems',
    'technologies',
    'users',
    'vortals');

$bs_noun_sing = array(
    'action-item',
    'application',
    'architecture',
    'bandwidth',
    'channel',
    'community',
    'content',
    'convergence',
    'deliverable',
    'e-business',
    'e-commerce',
    'e-market',
    'e-service',
    'e-tailer',
    'experience',
    'eyeball',
    'functionality',
    'infomediary',
    'infrastructure',
    'initiative',
    'interface',
    'market',
    'methodology',
    'metric',
    'mindshare',
    'model',
    'network',
    'niche',
    'paradigm',
    'partnership',
    'platform',
    'portal',
    'relationship',
    'ROI',
    'synergy',
    'web-readines',
    'schema',
    'solution',
    'supply-chain',
    'system',
    'technology',
    'user',
    'vortal');

$bs_job_one = array(
    'Lead',
    'Senior',
    'Direct',
    'Corporate',
    'Dynamic',
    'Future',
    'Product',
    'Regional',
    'District',
    'Central',
    'Global',
    'Customer',
    'Investor',
    'Dynamic',
    'International',
    'Legacy',
    'Forward',
    'Internal',
    'Human',
    'Chief',
    'Principal');

$bs_job_two = array(
    'Solutions',
    'Program',
    'Brand',
    'Security',
    'Research',
    'Marketing',
    'Directives',
    'Implementation',
    'Integration',
    'Functionality',
    'Response',
    'Paradigm',
    'Tactics',
    'Identity',
    'Markets',
    'Group',
    'Division',
    'Applications',
    'Optimization',
    'Operations',
    'Infrastructure',
    'Intranet',
    'Communications',
    'Web',
    'Branding',
    'Quality',
    'Assurance',
    'Mobility',
    'Accounts',
    'Data',
    'Creative',
    'Configuration',
    'Accountability',
    'Interactions',
    'Factors',
    'Usability',
    'Metrics');

$bs_job_three = array(
    'Supervisors',
    'Associates',
    'Executives',
    'Liasons',
    'Officers',
    'Managers',
    'Engineers',
    'Specialists',
    'Directors',
    'Coordinators',
    'Administrators',
    'Architects',
    'Analysts',
    'Designers',
    'Planners',
    'Orchestrators',
    'Technicians',
    'Developers',
    'Producers',
    'Consultants',
    'Assistants',
    'Facilitators',
    'Agents',
    'Representatives',
    'Strategists');


function bs() {
  global $bs_job_one, $bs_job_two, $bs_job_three;
  global $bs_verb, $bs_adj, $bs_noun, $bs_noun_sing;

  //$r  = $bs_adj[array_rand($bs_adj)]." ";
  $r  = $bs_job_one[array_rand($bs_job_one)]." ";
  $r .= $bs_job_two[array_rand($bs_job_two)]." ";
  $r .= $bs_job_three[array_rand($bs_job_three)].", ";
  $r .= " always, ";
  $r .= $bs_verb[array_rand($bs_verb)].", ";
  $r .= $bs_adj[array_rand($bs_adj)].", ";
  $r .= $bs_noun[array_rand($bs_noun)]."!";
  //$r .= $bs_noun_sing[array_rand($bs_noun_sing)];
  return $r;
}
 

?>
